security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity: { class: App\Entity\User, property: email }

  firewalls:
    dev: { pattern: ^/(_(profiler|wdt)|css|images|js)/, security: false }

    login:
      pattern: ^/api/auth/login
      stateless: true
      json_login:
        check_path:       /api/auth/login
        username_path:    email
        password_path:    password
        success_handler:  lexik_jwt_authentication.handler.authentication_success
        failure_handler:  lexik_jwt_authentication.handler.authentication_failure
      login_throttling:
        max_attempts: 5
        interval: '1 minute'

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

    docs:
      pattern: ^/api/docs
      stateless: true
      security: false  # ✅ totalement public

  access_control:
      - { path: ^/api/docs, roles: PUBLIC_ACCESS }
      - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
      - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
