api_login:
    path: /api/auth/login
    controller: App\Controller\AuthController::login
    methods: [POST]

api_products:
    path: /api/products
    controller: App\Controller\ProductController::list
    methods: [GET]

api_subscriptions_my:
    path: /api/subscriptions
    controller: App\Controller\SubscriptionController::getUserSubscription
    methods: [GET]

api_subscriptions_create:
    path: /api/subscriptions
    controller: App\Controller\SubscriptionController::create
    methods: [POST]

api_subscriptions_cancel:
    path: /api/subscriptions/{id}/cancel
    controller: App\Controller\SubscriptionController::cancel
    methods: [POST]

controllers:
    resource: ../src/Controller/
    type: attribute


