version: "3.9"
services:
  php:
    build:
      context: ../subscription-app
      target: app
    container_name: subscriptions-php
    environment:
      APP_ENV: dev
      DATABASE_URL: ${DATABASE_URL:-mysql://symfony:symfony@db:3306/app?charset=utf8mb4}
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
    volumes:
      - ../subscription-app:/var/www/subscriptions-api/subscription-app:delegated
    depends_on: [db]

  nginx:
    build: ./nginx
    container_name: subscriptions-nginx
    ports: ["8080:80"]
    volumes:
      - ../subscription-app:/var/www/subscriptions-api/subscription-app:ro
    depends_on: [php]

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    ports: ["3307:3306"]   # change si 3306 libre
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: {}
